# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.6.17-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pruebas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./var/lib/mysql:/var/lib/mysql       
      - ./var/lib/backup/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ":3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
